version: '3.8'

services:
  express:
    depends_on:
      - mongo
      - redis
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    environment:
      - CONNECTION_URL=mongodb://mongo:27017
      - SECRET_KEY=CAN_CHANGE_TO_ANYTHING
      - PORT=5000
      - NODE_ENV=development
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    command: npm run dev

  mongo:
    image: mongo:5.0.18
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo_dump:/data/db

  redis:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_dump:/data

volumes:
  mongo_dump:
  redis_dump:
